[package]
name = "ansi_swatch"
version = "0.1.0"
authors = ["Kevin Smith <kevin@kevinsmith.cc>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
